language: csharp
mono: none
dotnet: 3.1
solution: HelloCI.sln
script:
 - cd HelloCI
 - cd ..
 - cd HelloCI
 - dotnet restore
 - dotnet build
 - dotnet test HelloCI-Test/HelloCI-Test.csproj
deploy:
  provider: releases
  token: TRAVIS_DATA
  file: HelloCIApp
